<?php

namespace WebService\Bundle\MoteurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MobileUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileUserRepository extends EntityRepository
{
}
